# 파이썬 기본문법 

In [1]:
abc = 123456
print(abc + 100) 

123556


In [2]:
string1 ="Python is "
sgring2 = "powerful"

print(string1 + sgring2)


Python is powerful


In [3]:
type (123) #type 정수

int

In [5]:
type(123.45) #실수 

float

In [6]:
5+2 

7

In [11]:
print(5+2) # Addiction
print(5-2) # Substraction 
print(5*2) # Multiply 
print(5/2) #Devision 
print(5//2) #main 
print(5%2) #Remaining
print(5**2) #Squeir 

7
3
10
2.5
2
1
25


In [14]:
#String 
print(type("String"))

<class 'str'>


In [15]:
str = "Hello World!"
len(str) #length of string 

12

In [19]:
print("""
Multi line comment 
it working 
likt this weay 
!!!

""")


Multi line comment 
it working 
likt this weay 
!!!




In [22]:
#비교연산 
a = 1 
b = 3
print(a<b)

#논리연산 
print(True and True) 
print(True and False) 


True
True
False


In [25]:
#list 
list_num = [10,20,30,40,50]
list_str = ["programming","launge","python"]
list_mix  = [1.5, 8, "String1", [1,2,3]]

In [ ]:
#연산자 : only *,+ 

In [27]:
#indexing : list_data[i]

list_num[0]

10

In [28]:
list_num[1] = 100

In [29]:
print(list_num)

[10, 100, 30, 40, 50]


In [31]:
print(list_num[0:4])
print(list_num[:3])

[10, 100, 30, 40]
[10, 100, 30]


In [37]:
print(list_num[-1])

50


In [44]:
print(list_num[0:-1])

[10, 100, 30, 40]


In [45]:
print(list_num[0:-2])

[10, 100, 30]


In [46]:
#append(), insert(loc, num ) , extend() 끝에추가 
#remove() 첫번째 일치하는 항목 학제 
#pop() 마지막요소 제거 및 리턴 
#count() 
#sort()
#reverse() 

In [47]:
#tupple 
tuple_data = (1,2,3,4,5,6,)

In [49]:
print(tuple_data)

(1, 2, 3, 4, 5, 6)


In [50]:
type(tuple_data)

tuple

In [51]:
#for loop 

for num in [0,1,2,3,4,5,6,7,8,9]:
    print(num,)

0
1
2
3
4
5
6
7
8
9


In [52]:
list(range(0,10,1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
for num in range(10):
    print(num)

0
1
2
3
4
5
6
7
8
9


In [59]:
list_num = [10,20,30,40]

for index, value in enumerate (list_num):
    print(index, value)

0 10
1 20
2 30
3 40


In [61]:
name = ["a","b","c","d","e","f"]
scores = [96,85,100,70,80,75]

In [63]:
for k in range(len(name)):
    print(name[k], scores[k])

a 96
b 85
c 100
d 70
e 80
f 75


In [64]:
# zip 하나로 묵는다..튜플 

for name, score in zip(name, scores):
    print(name,score)

a 96
b 85
c 100
d 70
e 80
f 75


In [65]:
list_num = [] 
count = 0

while(count<10):
    list_num.append(count)
    count = count + 1
    

    
print(list_num)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# break -> 무조건 빠저나온다.
#continue = 지나가서 다시 루프를 돈다. 


In [68]:
number=[0,1,2,3,4,5,6,7,8,9]
result = [2*x+1 for x in number]
print(result)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [69]:
result2= [2*x+1 for x in number if x>=3]

In [70]:
print(result2)

[7, 9, 11, 13, 15, 17, 19]


# 함수 클래스 

In [90]:
def my_emotion():
    print("=" *20)
    print("Sad")
    print("=" *20)
    

#함수의 호출 
my_emotion() 

Sad


In [104]:
class Robot(): 
    def __init__(name, position):
        self.name = name 
        self.position = position
        
    def move(self):
        self.position = self.position + 1
        print(f"self.name 의 현위치 : {self.position}")

In [105]:
robot1 = Robot("R1", 10)

TypeError: Robot.__init__() takes 2 positional arguments but 3 were given

In [106]:
import numpy as np 


In [109]:
list_data = [0,1,2,3,4,5,6,7,8,9]

In [110]:
arr  = np.array(list_data)

In [111]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [112]:
type(arr)

numpy.ndarray

In [113]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [114]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [116]:
ar = np.arange(10)

In [121]:
print(type(ar))
print(type([ar]))

<class 'numpy.ndarray'>
<class 'list'>


In [122]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [123]:
np.linspace(0,np.pi,20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [124]:
a1= np.array ([0,10,20,30,40,50,60,70,80,90])

In [125]:
a1[0]

0

In [126]:
a1[2]

20

In [127]:
a1[-2]

80

In [131]:
a1[[4,0,5,-5,-2]]

array([40,  0, 50, 50, 80])

In [132]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [133]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a[a>=5]

array([5, 6, 7, 8, 9])

In [135]:
a[(a%2)==0]

array([0, 2, 4, 6, 8])

In [138]:
a[((a%2)==0) & (a<5)]

array([0, 2, 4])

In [139]:

import pandas as pd

In [140]:
x1 = pd.Series([10,20,30,40,50])

In [141]:
print(x1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [143]:
x1.index

RangeIndex(start=0, stop=5, step=1)

In [144]:
x1.values

array([10, 20, 30, 40, 50])

In [145]:
x1.values[x1>30]

array([40, 50])

In [146]:
type(x1)

pandas.core.series.Series

In [150]:
i_dat=[10,20,30,40]
data = ["a","b","c","e"]

s2 = pd.Series(data,index = i_dat)


In [151]:
print(s2)

10    a
20    b
30    c
40    e
dtype: object


In [152]:
s1.index

NameError: name 's1' is not defined

In [153]:
s2.index

Index([10, 20, 30, 40], dtype='int64')

In [160]:
s2.index[s2>10]

TypeError: '>' not supported between instances of 'str' and 'int'

In [161]:
data = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(data)

In [162]:
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [163]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [166]:
print(data)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [165]:
type(data)

numpy.ndarray

In [169]:
index_date = pd.date_range('2023-01-11', periods=4)

In [171]:
column_data =['A','B','C']

In [175]:
df2 = pd.DataFrame(data,index= index_date, columns=column_data)

In [176]:
print(df2)

             A   B   C
2023-01-11   1   2   3
2023-01-12   4   5   6
2023-01-13   7   8   9
2023-01-14  10  11  12


In [182]:
df2['B']

2023-01-11     2
2023-01-12     5
2023-01-13     8
2023-01-14    11
Freq: D, Name: B, dtype: int64

In [184]:
df2[:]

A   B   C
2023-01-11   1   2   3
2023-01-12   4   5   6
2023-01-13   7   8   9
2023-01-14  10  11  12

In [186]:
df2.columns

Index(['A', 'B', 'C'], dtype='object')

In [188]:
df2.index

DatetimeIndex(['2023-01-11', '2023-01-12', '2023-01-13', '2023-01-14'], dtype='datetime64[ns]', freq='D')

In [190]:
df2.values

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [192]:
df2.set_index("C")

A   B
C         
3    1   2
6    4   5
9    7   8
12  10  11

In [193]:
df2

A   B   C
2023-01-11   1   2   3
2023-01-12   4   5   6
2023-01-13   7   8   9
2023-01-14  10  11  12

In [194]:
dict_data = {'A':[10,20,30,40,],
            'B': [0.1,0.3,0.3,0.4],
            'C': [100,200,300,400]}

In [195]:
df3 = pd.DataFrame(dict_data)

In [197]:
print(df3)

    A    B    C
0  10  0.1  100
1  20  0.3  200
2  30  0.3  300
3  40  0.4  400


In [199]:
df3.reindex([2,0,1,3])

A    B    C
2  30  0.3  300
0  10  0.1  100
1  20  0.3  200
3  40  0.4  400

In [ ]:

df = pd.read_csv(