In [56]:
import pandas as pd
import numpy as np

In [3]:
s1 = pd.Series([10,20,30,40,50])

In [4]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
np1 = np.array(s1)

In [7]:
np1

array([10, 20, 30, 40, 50])

In [15]:
data = [[1,2,3],[4,5,6],[7,8,9]]
print(data)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
np1 = np.array(data)

In [14]:
print(np1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
np1[np1<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
df = pd.DataFrame(np1)

In [20]:
df2 = pd.DataFrame(data)

In [21]:
print(df)
print(df2)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [23]:
data = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [50]:
index_data = pd.date_range('2023-01-11', periods=4)
index_data

DatetimeIndex(['2023-01-11', '2023-01-12', '2023-01-13', '2023-01-14'], dtype='datetime64[ns]', freq='D')

In [47]:
columns_data = ['A','B','C']

In [53]:
df = pd.DataFrame(data, index_data, columns_data)

In [54]:
df

A   B   C
2023-01-11   1   2   3
2023-01-12   4   5   6
2023-01-13   7   8   9
2023-01-14  10  11  12

In [59]:
dict_data = {'연도': [2021,2021,2022,2022],
             '지사': ['한국','미국','한국','미국'],
             '고객수': [200, np.nan, 250,450]}   

In [60]:
df = pd.DataFrame(dict_data)

In [61]:
df

연도  지사    고객수
0  2021  한국  200.0
1  2021  미국    NaN
2  2022  한국  250.0
3  2022  미국  450.0

In [62]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [63]:
df.columns

Index(['연도', '지사', '고객수'], dtype='object')

In [67]:
val = df.values

In [68]:
type(val)

numpy.ndarray

In [81]:
data = val[[0,3]]

In [82]:
print(data)

[[2021 '한국' 200.0]
 [2022 '미국' 450.0]]


In [84]:
ps_df = pd.read_csv('A_product_sales.csv')
                

In [85]:
ps_df

연도   1분기   2분기   3분기   4분기
0  2016  2412  4032  5183  1139
1  2017  2725  4986  6015  1242
2  2018  2925  5286  6497  1596
3  2019  2691  5813  7202  1358
4  2020  2523  6137  7497  1512

In [86]:
s1 = pd.Series([10,20,30])

In [87]:
s2 = pd.Series([40,50,60])

In [88]:
s3 = pd.Series([70,80,90])

In [90]:
pd.concat([s1,s2],ignore_index=True)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [91]:
import requests

In [93]:
r = requests.get('https://www.google.co.kr') 

In [94]:
r

<Response [200]>

In [95]:
r.status_code

200

In [96]:
type(r)

requests.models.Response

In [100]:
r.text[0:100]

'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ko"><head><meta content'

In [103]:
from bs4 import BeautifulSoup




In [104]:
r.headers

{'Date': 'Tue, 03 Oct 2023 13:41:36 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=EUC-KR', 'Content-Security-Policy-Report-Only': "object-src 'none';base-uri 'self';script-src 'nonce-ms0jmwrI97Ln-vNqmzkTRw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp", 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': '1P_JAR=2023-10-03-13; expires=Thu, 02-Nov-2023 13:41:36 GMT; path=/; domain=.google.co.kr; Secure, AEC=Ackid1SrZqXp61Ypu4jpK8_AjC3Oo0jZTvBMnYoISTDtXiEGxz3cz2yKzg; expires=Sun, 31-Mar-2024 13:41:36 GMT; path=/; domain=.google.co.kr; Secure; HttpOnly; SameSite=lax, NID=511=QXLX5K6NFmdaSHOwt3Kr52Roq2zgiBy-U45EW2XWIUam9aV_4mODRVHXVoa64NwtGg_qkVwNuZYG_GhoURME-r4BLgn0BI726PH5zgmmqaJIT2yvKjCF6q8Gm9GK7UujtnJjxcGIFTVNXPixX

In [105]:
html = r.text
html[0:100]

'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ko"><head><meta content'

In [106]:
soup = BeautifulSoup(html,'lxml')

In [109]:
type (soup.headers)

NoneType

In [111]:
print(soup.headers)

None


In [112]:
# 테스트용 html 소스
html = """<html><body><div><span>\
        <a href=http://www.naver.com>naver</a>\
        <a href=https://www.google.com>google</a>\
        <a href=http://www.daum.net/>daum</a>\
        </span></div></body></html>""" 

# BeautifulSoup를 이용해 HTML 소스를 파싱
soup = BeautifulSoup(html, 'lxml') 
soup

<html><body><div><span> <a href="http://www.naver.com">naver</a> <a href="https://www.google.com">google</a> <a href="http://www.daum.net/">daum</a> </span></div></body></html>

In [114]:
print(soup.prettify())

<html>
 <body>
  <div>
   <span>
    <a href="http://www.naver.com">
     naver
    </a>
    <a href="https://www.google.com">
     google
    </a>
    <a href="http://www.daum.net/">
     daum
    </a>
   </span>
  </div>
 </body>
</html>



In [116]:
soup.find('a') # 처음 a tab 전체 요소 를 리턴한다. 

<a href="http://www.naver.com">naver</a>

In [117]:
first_a = soup.find('a')

In [121]:
type(first_a.get_text())

str

In [125]:
get_text = first_a.get_text()

In [129]:
print(f"the first a tag's text is {get_text} ")  

the first a tag's text is naver 


In [131]:
get_href = first_a['href']

In [132]:
print(get_href)

http://www.naver.com


In [133]:
findall_result= soup.find_all('a')

In [134]:
print(findall_result)

[<a href="http://www.naver.com">naver</a>, <a href="https://www.google.com">google</a>, <a href="http://www.daum.net/">daum</a>]


In [146]:
for i in findall_result:
    print(i.get_text(),"address : ",i.get('href'))

naver address :  http://www.naver.com
google address :  https://www.google.com
daum address :  http://www.daum.net/


In [148]:
[x.get_text() for x in soup.find_all('a')]

['naver', 'google', 'daum']

In [188]:
html2 = """
<html>
 <head>
  <title>작품과 작가 모음</title>
 </head>
 <body>
  <h1>책 정보</h1>
  <p id="book_title">토지</p>
  <p id="author">박경리</p>
  
  <p id="book_title">태백산맥</p>
  <p id="author">조정래</p>

  <p id="book_title">감옥으로부터의 사색</p>
  <p id="author">신영복</p>
  </body>
</html>
""" 

In [189]:
soup2 = BeautifulSoup(html2,'lxml')

In [190]:
soup2.head

<head>
<title>작품과 작가 모음</title>
</head>

In [191]:
soup2.head.title

<title>작품과 작가 모음</title>

In [192]:
soup2.head.title.get_text()

'작품과 작가 모음'

In [193]:
soup2.body.p # 첫번째 하위 태그만 반환 

<p id="book_title">토지</p>

In [194]:
soup2.body.h1

<h1>책 정보</h1>

In [195]:
soup2.p

<p id="book_title">토지</p>

In [213]:
print(soup2.p["id"])

book_title


In [228]:
book_titles = soup2.find_all("p",{'id':'book_title'}) 

In [231]:
print(book_titles)

[<p id="book_title">토지</p>, <p id="book_title">태백산맥</p>, <p id="book_title">감옥으로부터의 사색</p>]


In [232]:
authors = soup2.find_all('p',{'id':'author'})

In [233]:
print(authors)

[<p id="author">박경리</p>, <p id="author">조정래</p>, <p id="author">신영복</p>]


In [235]:
for book_title, author in zip(book_titles,authors):
    print(book_title.get_text()+ ':' + author.get_text()) 


토지:박경리
태백산맥:조정래
감옥으로부터의 사색:신영복


In [236]:
# Select 사용하기
html2 = """
<html>
 <head>
  <title>작품과 작가 모음</title>
 </head>
 <body>
  <h1>책 정보</h1>
  <p id="book_title">토지</p>
  <p id="author">박경리</p>
  
  <p id="book_title">태백산맥</p>
  <p id="author">조정래</p>

  <p id="book_title">감옥으로부터의 사색</p>
  <p id="author">신영복</p>
  </body>
</html>
""" 

In [237]:
soup = BeautifulSoup(html2,'lxml')

In [245]:
book_title_author = soup.select_one('body h1')

In [246]:
print(book_title_author.get_text()) 

책 정보


In [247]:
book_titles = soup.select('p#book_title') 

In [248]:
print(book_titles)

[<p id="book_title">토지</p>, <p id="book_title">태백산맥</p>, <p id="book_title">감옥으로부터의 사색</p>]


In [249]:
book_authors = soup.select('p#author')

In [250]:
print(book_authors)

[<p id="author">박경리</p>, <p id="author">조정래</p>, <p id="author">신영복</p>]


In [251]:
for title, author in zip(book_titles, book_authors):
    print(title.get_text() , " : ", author.get_text())

토지  :  박경리
태백산맥  :  조정래
감옥으로부터의 사색  :  신영복


In [252]:
%%writefile ./HTML_example_my_site.html 

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>사이트 모음</title>
  </head>
  <body>
    <p id="title"><b>자주 가는 사이트 모음</b></p>
    <p id="contents">이곳은 자주 가는 사이트를 모아둔 곳입니다.</p>
    <a href="http://www.naver.com" class="portal" id="naver">네이버</a> <br>
    <a href="https://www.google.com" class="search" id="google">구글</a> <br>
    <a href="http://www.daum.net" class="portal" id="daum">다음</a> <br>
    <a href="http://www.nl.go.kr" class="government" id="nl">국립중앙도서관</a>
  </body>
</html>

Writing ./HTML_example_my_site.html


In [253]:
f = open('./HTML_example_my_site.html', encoding='utf-8')

In [254]:
html3 = f.read()

In [255]:
f.close()

In [256]:
print(html3[0:100])


<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>사이트 모음</title>
  </head>
  <b


In [257]:
soup3 = BeautifulSoup(html3, 'lxml') 

In [258]:
type(soup3)

bs4.BeautifulSoup

In [259]:
print(soup3.prettify())

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8"/>
  <title>
   사이트 모음
  </title>
 </head>
 <body>
  <p id="title">
   <b>
    자주 가는 사이트 모음
   </b>
  </p>
  <p id="contents">
   이곳은 자주 가는 사이트를 모아둔 곳입니다.
  </p>
  <a class="portal" href="http://www.naver.com" id="naver">
   네이버
  </a>
  <br/>
  <a class="search" href="https://www.google.com" id="google">
   구글
  </a>
  <br/>
  <a class="portal" href="http://www.daum.net" id="daum">
   다음
  </a>
  <br/>
  <a class="government" href="http://www.nl.go.kr" id="nl">
   국립중앙도서관
  </a>
 </body>
</html>



In [260]:
soup3.select('a')

[<a class="portal" href="http://www.naver.com" id="naver">네이버</a>,
 <a class="search" href="https://www.google.com" id="google">구글</a>,
 <a class="portal" href="http://www.daum.net" id="daum">다음</a>,
 <a class="government" href="http://www.nl.go.kr" id="nl">국립중앙도서관</a>]

In [263]:
soup3.select('a.portal#naver')

[<a class="portal" href="http://www.naver.com" id="naver">네이버</a>]