In [2]:
import numpy as np

In [10]:
list_data = [0,1,2,3,4,5,6,7,8,9.0]
type(list_data)


list

In [14]:
a1 = np.array(list_data)

#리스트 를 Array 모 만들어줌 

In [16]:
print(a1)
type(a1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


numpy.ndarray

In [31]:
list_2 = [a1[0],a1[3],a1[4]]

list_2 #안된다. 

[0.0, 3.0, 4.0]

In [33]:
#여러개의 요소를 가지고 오기 

a2 = np.array([0,10,20,30,40,50])

a2[[4,0,5,-1,-2]]


array([40,  0, 50, 50, 40])

In [36]:
list_3 = a1[[0,3,4]]

In [38]:
print(list_3) #위에 각각의 인덱스를 사용하는 것도 동일한 결과임. 


[0. 3. 4.]


In [39]:
a3 = np.arange(10)

In [40]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [41]:
a[a>=5] #인덱스 대신 조건 condition 을 넣을수 있다. 

array([5, 6, 7, 8, 9])